In [2]:
#Loading libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
#Importing the Dataset- Iris dataset
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [4]:
#Feature engineering

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Reading dataset to pandas dataframe
irisdata=pd.read_csv(url, names=colnames)

#preprocessing the data

#x is the attributes (what we're using to predict)
x=irisdata.drop('Class', axis=1)
#y is the label (what we're trying to predict)
y=irisdata['Class']

In [5]:
#Training Testing Splitting

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2)

#Training the Algorithm
''' In order to train a kernel SVM we use the same SVC class.
The difference between a kernel SVM and the simple SVM is in the value for the kernel parameter of the SVC class:
In simple SVM we used linear, but here we can use Gaussian, polynomial, sigmoid, or computable kernel'''

#1. Polynomial Kernel
#If you want to use a polynomial kernel, you need to pass an additional value for the degree parameter of the SVC class (The degee of the polynomial)

from sklearn.svm import SVC
svclassifier= SVC(kernel='poly', degree=8)
svclassifier.fit(x_train, y_train)

#Making Predictions
y_predict=svclassifier.predict(x_test)

#Evaluating the Algorithm

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test,y_predict))

[[ 9  0  0]
 [ 0 10  1]
 [ 0  1  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.91      0.91      0.91        11
 Iris-virginica       0.90      0.90      0.90        10

      micro avg       0.93      0.93      0.93        30
      macro avg       0.94      0.94      0.94        30
   weighted avg       0.93      0.93      0.93        30



c:\users\sagi\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [6]:
#2. Gaussian Kernel
from sklearn.svm import SVC
svclassifier=SVC(kernel='rbf')
svclassifier.fit(x_train, y_train)

#Prediction and Evaluation
y_predict=svclassifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test,y_predict))

[[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      0.91      0.95        11
 Iris-virginica       0.91      1.00      0.95        10

      micro avg       0.97      0.97      0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



c:\users\sagi\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [7]:
#3. Sigmoid Kernel
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)

#Prediction and Evaluation
y_pred = svclassifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

#Sigmoid function returns two values: 0 and 1, therefore it is better to use it in binary classification problems. 
#Hence the bad score (we had 3 classes) in this example.

[[ 9  0  0]
 [11  0  0]
 [10  0  0]]
                 precision    recall  f1-score   support

    Iris-setosa       0.30      1.00      0.46         9
Iris-versicolor       0.00      0.00      0.00        11
 Iris-virginica       0.00      0.00      0.00        10

      micro avg       0.30      0.30      0.30        30
      macro avg       0.10      0.33      0.15        30
   weighted avg       0.09      0.30      0.14        30



c:\users\sagi\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\sagi\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
